server:
  port: 8080

spring:
  application:
    name: employee-app

  config:
    import: "optional:configserver:http://localhost:8888"
    
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


  cache:
    type: caffeine
    cache-names: employeeCache
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, caches, refresh
  endpoint:
    health:
      show-details: always
