server:
  port: 8081

spring:
  application:
    name: employee-app

  cache:
    type: caffeine
    cache-names: employeeCache
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, caches, refresh
  endpoint:
    health:
      show-details: always
